spring.application.name=demo
# spring.profiles.include=secret
# spring.config.import=application-secret.properties

## mybatis setting
## RDS endpoint=naranghiking.ch4s62qa68pz.ap-southeast-2.rds.amazonaws.com
#spring.datasource.url=jdbc:mysql://localhost:3306/NarangHiking?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.url=jdbc:mysql://${DB_ENDPOINT}:3306/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.naranghiking

# Sql
spring.sql.init.mode=always

## MyBatis 관련 설정
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.com.naranghiking.board.dao=DEBUG

jwt.secret=naranghiking-secret-key-must-be-at-least-32-bytes
jwt.access-expiration=1800000
jwt.refresh-expiration=604800000

spring.data.redis.host=localhost
spring.data.redis.port=6379

## 디버깅
logging.level.org.springframework.security=DEBUG
logging.level.com.naranghiking=DEBUG
logging.level.org.mybatis=DEBUG

# image upload path
file.images-dir=../uploads/images/

# ?? API ?
data.api.key=${DATA_API_KEY}

# db ?? ?? ??
cloudflare.r2.account-id=${CLOUDFLARE.R2.ACCOUNT-ID}
cloudflare.r2.access-key=${CLOUDFLARE.R2.ACCESS-KEY}
cloudflare.r2.secret-key=${CLOUDFLARE.R2.SECRET-KEY}
cloudflare.r2.bucket-name=${CLOUDFLARE.R2.BUCKET-NAME}
cloudflare.r2.public-base-url=${CLOUDFLARE.R2.PUBLIC-BASE-URL}
## swagger 주소
## http://localhost:8080/swagger-ui/index.html#