??spring.application.name=demo

## mybatis setting
spring.datasource.url=jdbc:mysql://localhost:3306/NarangHiking?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.naranghiking

spring.data.redis.host=localhost
spring.data.redis.port=6379